GRANT ALL ON GABYVAL.AD_ERROR TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_EXECUTE_JOB TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_ID_CONTROL TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_JOB TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_MODULE_CONFIGURATION TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_NO_WORKING_DAYS TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_RESOURCE TO JAVA_ADMIN;
GRANT ALL ON GABYVAL.AD_SYSTEM_CONTROL TO JAVA_ADMIN;
COMMIT;