package com.gabyval.core.scheduler;
// Generated May 21, 2017 4:30:45 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdExecuteJob generated by hbm2java
 */
@Entity
@Table(name="AD_EXECUTE_JOB"
    ,schema="GABYVAL"
)
public class AdExecuteJob  implements java.io.Serializable {


     private int gbJobId;
     private int gbRunState;
     private Date gbLastExec;
     private String gbMsgError;
     private int gbExecTime;
     private Date createDt;
     private int rowversion;

    public AdExecuteJob() {
    }

    public AdExecuteJob(int gbJobId, int gbRunState, Date gbLastExec, String gbMsgError, int gbExecTime, Date createDt, int rowversion) {
       this.gbJobId = gbJobId;
       this.gbRunState = gbRunState;
       this.gbLastExec = gbLastExec;
       this.gbMsgError = gbMsgError;
       this.gbExecTime = gbExecTime;
       this.createDt = createDt;
       this.rowversion = rowversion;
    }
   
     @Id 

    
    @Column(name="GB_JOB_ID", unique=true, nullable=false, precision=22, scale=0)
    public int getGbJobId() {
        return this.gbJobId;
    }
    
    public void setGbJobId(int gbJobId) {
        this.gbJobId = gbJobId;
    }

    
    @Column(name="GB_RUN_STATE", nullable=false, precision=22, scale=0)
    public int getGbRunState() {
        return this.gbRunState;
    }
    
    public void setGbRunState(int gbRunState) {
        this.gbRunState = gbRunState;
    }

    
    @Column(name="GB_LAST_EXEC", nullable=false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getGbLastExec() {
        return this.gbLastExec;
    }
    
    public void setGbLastExec(Date gbLastExec) {
        this.gbLastExec = gbLastExec;
    }

    
    @Column(name="GB_MSG_ERROR", nullable=true, length=200)
    public String getGbMsgError() {
        return this.gbMsgError;
    }
    
    public void setGbMsgError(String gbMsgError) {
        this.gbMsgError = gbMsgError;
    }

    
    @Column(name="GB_EXEC_TIME", nullable=false, precision=22, scale=0)
    public int getGbExecTime() {
        return this.gbExecTime;
    }
    
    public void setGbExecTime(int gbExecTime) {
        this.gbExecTime = gbExecTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public int getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(int rowversion) {
        this.rowversion = rowversion;
    }
}
