package com.gabyval.persistence.user.security;
// Generated 8/09/2018 01:25:28 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdPwdHistory generated by hbm2java
 */
@Entity
@Table(name="AD_PWD_HISTORY"
    ,schema="GABYVAL"
)
public class AdPwdHistory  implements java.io.Serializable {


     private AdPwdHistoryId id;
     private Date gbPwdInsDt;
     private Date createDt;
     private BigDecimal rowversion;

    public AdPwdHistory() {
    }

    public AdPwdHistory(AdPwdHistoryId id, Date gbPwdInsDt, Date createDt, BigDecimal rowversion) {
       this.id = id;
       this.gbPwdInsDt = gbPwdInsDt;
       this.createDt = createDt;
       this.rowversion = rowversion;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="gbPwdSaved", column=@Column(name="GB_PWD_SAVED", nullable=false, length=200) ), 
        @AttributeOverride(name="gbUsername", column=@Column(name="GB_USERNAME", nullable=false, length=20) ) } )
    public AdPwdHistoryId getId() {
        return this.id;
    }
    
    public void setId(AdPwdHistoryId id) {
        this.id = id;
    }

    
    @Column(name="GB_PWD_INS_DT", nullable=false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getGbPwdInsDt() {
        return this.gbPwdInsDt;
    }
    
    public void setGbPwdInsDt(Date gbPwdInsDt) {
        this.gbPwdInsDt = gbPwdInsDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public BigDecimal getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(BigDecimal rowversion) {
        this.rowversion = rowversion;
    }




}


