package com.gabyval.persistence.user.security;
// Generated 8/09/2018 01:25:28 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdPwdHistoryId generated by hbm2java
 */
@Embeddable
public class AdPwdHistoryId  implements java.io.Serializable {


     private String gbPwdSaved;
     private String gbUsername;

    public AdPwdHistoryId() {
    }

    public AdPwdHistoryId(String gbPwdSaved, String gbUsername) {
       this.gbPwdSaved = gbPwdSaved;
       this.gbUsername = gbUsername;
    }
   


    @Column(name="GB_PWD_SAVED", nullable=false, length=200)
    public String getGbPwdSaved() {
        return this.gbPwdSaved;
    }
    
    public void setGbPwdSaved(String gbPwdSaved) {
        this.gbPwdSaved = gbPwdSaved;
    }


    @Column(name="GB_USERNAME", nullable=false, length=20)
    public String getGbUsername() {
        return this.gbUsername;
    }
    
    public void setGbUsername(String gbUsername) {
        this.gbUsername = gbUsername;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdPwdHistoryId) ) return false;
		 AdPwdHistoryId castOther = ( AdPwdHistoryId ) other; 
         
		 return ( (this.getGbPwdSaved()==castOther.getGbPwdSaved()) || ( this.getGbPwdSaved()!=null && castOther.getGbPwdSaved()!=null && this.getGbPwdSaved().equals(castOther.getGbPwdSaved()) ) )
 && ( (this.getGbUsername()==castOther.getGbUsername()) || ( this.getGbUsername()!=null && castOther.getGbUsername()!=null && this.getGbUsername().equals(castOther.getGbUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGbPwdSaved() == null ? 0 : this.getGbPwdSaved().hashCode() );
         result = 37 * result + ( getGbUsername() == null ? 0 : this.getGbUsername().hashCode() );
         return result;
   }   


}


