package com.gabyval.persistence.user.security;
// Generated Jul 29, 2017 1:26:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdSecMenuProfilingId generated by hbm2java
 */
@Embeddable
public class AdSecMenuProfilingId  implements java.io.Serializable {


     private String gbMenuId;
     private String gbProfileName;

    public AdSecMenuProfilingId() {
    }

    public AdSecMenuProfilingId(String gbMenuId, String gbProfileName) {
       this.gbMenuId = gbMenuId;
       this.gbProfileName = gbProfileName;
    }
   


    @Column(name="GB_MENU_ID", nullable=false, length=100)
    public String getGbMenuId() {
        return this.gbMenuId;
    }
    
    public void setGbMenuId(String gbMenuId) {
        this.gbMenuId = gbMenuId;
    }


    @Column(name="GB_PROFILE_NAME", nullable=false, length=100)
    public String getGbProfileName() {
        return this.gbProfileName;
    }
    
    public void setGbProfileName(String gbProfileName) {
        this.gbProfileName = gbProfileName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdSecMenuProfilingId) ) return false;
		 AdSecMenuProfilingId castOther = ( AdSecMenuProfilingId ) other; 
         
		 return ( (this.getGbMenuId()==castOther.getGbMenuId()) || ( this.getGbMenuId()!=null && castOther.getGbMenuId()!=null && this.getGbMenuId().equals(castOther.getGbMenuId()) ) )
 && ( (this.getGbProfileName()==castOther.getGbProfileName()) || ( this.getGbProfileName()!=null && castOther.getGbProfileName()!=null && this.getGbProfileName().equals(castOther.getGbProfileName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGbMenuId() == null ? 0 : this.getGbMenuId().hashCode() );
         result = 37 * result + ( getGbProfileName() == null ? 0 : this.getGbProfileName().hashCode() );
         return result;
   }   


}


