package com.gabyval.persistence.user.security;
// Generated 19/11/2017 07:26:33 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdSecMenulinks generated by hbm2java
 */
@Entity
@Table(name="AD_SEC_MENULINKS"
    ,schema="GABYVAL"
)
public class AdSecMenulinks  implements java.io.Serializable {


     private String gbMenuId;
     private String gbMenuName;
     private String gbMenuParId;
     private String gbPageView;
     private int gbMenuStatus;
     private Date createDt;
     private int rowversion;
     private String gbLastUserChg;
     private Date gbLastDateChg;

    public AdSecMenulinks() {
    }

	
    public AdSecMenulinks(String gbMenuId, String gbMenuName, int gbMenuStatus, Date createDt, int rowversion) {
        this.gbMenuId = gbMenuId;
        this.gbMenuName = gbMenuName;
        this.gbMenuStatus = gbMenuStatus;
        this.createDt = createDt;
        this.rowversion = rowversion;
    }
    public AdSecMenulinks(String gbMenuId, String gbMenuName, String gbMenuParId, String gbPageView, int gbMenuStatus, Date createDt, int rowversion, String gbLastUserChg, Date gbLastDateChg) {
       this.gbMenuId = gbMenuId;
       this.gbMenuName = gbMenuName;
       this.gbMenuParId = gbMenuParId;
       this.gbPageView = gbPageView;
       this.gbMenuStatus = gbMenuStatus;
       this.createDt = createDt;
       this.rowversion = rowversion;
       this.gbLastUserChg = gbLastUserChg;
       this.gbLastDateChg = gbLastDateChg;
    }
   
     @Id 

    
    @Column(name="GB_MENU_ID", unique=true, nullable=false, length=100)
    public String getGbMenuId() {
        return this.gbMenuId;
    }
    
    public void setGbMenuId(String gbMenuId) {
        this.gbMenuId = gbMenuId;
    }

    
    @Column(name="GB_MENU_NAME", nullable=false, length=150)
    public String getGbMenuName() {
        return this.gbMenuName;
    }
    
    public void setGbMenuName(String gbMenuName) {
        this.gbMenuName = gbMenuName;
    }

    
    @Column(name="GB_MENU_PAR_ID", length=100)
    public String getGbMenuParId() {
        return this.gbMenuParId;
    }
    
    public void setGbMenuParId(String gbMenuParId) {
        this.gbMenuParId = gbMenuParId;
    }

    
    @Column(name="GB_PAGE_VIEW", length=100)
    public String getGbPageView() {
        return this.gbPageView;
    }
    
    public void setGbPageView(String gbPageView) {
        this.gbPageView = gbPageView;
    }

    
    @Column(name="GB_MENU_STATUS", nullable=false, precision=22, scale=0)
    public int getGbMenuStatus() {
        return this.gbMenuStatus;
    }
    
    public void setGbMenuStatus(int gbMenuStatus) {
        this.gbMenuStatus = gbMenuStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public int getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(int rowversion) {
        this.rowversion = rowversion;
    }

    
    @Column(name="GB_LAST_USER_CHG", length=20)
    public String getGbLastUserChg() {
        return this.gbLastUserChg;
    }
    
    public void setGbLastUserChg(String gbLastUserChg) {
        this.gbLastUserChg = gbLastUserChg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GB_LAST_DATE_CHG")
    public Date getGbLastDateChg() {
        return this.gbLastDateChg;
    }
    
    public void setGbLastDateChg(Date gbLastDateChg) {
        this.gbLastDateChg = gbLastDateChg;
    }




}


