package com.gabyval.persistence.user.security;
// Generated Jul 29, 2017 1:26:07 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdUserProfile generated by hbm2java
 */
@Entity
@Table(name="AD_USER_PROFILE"
    ,schema="GABYVAL"
)
public class AdUserProfile  implements java.io.Serializable {


     private String gbProfileName;
     private String gbProfileDesc;
     private int gbProfileStatus;
     private String gbUserCreate;
     private String gbLastUserUp;
     private Date gbLastUpDt;
     private Date createDt;
     private int rowversion;

    public AdUserProfile() {
    }

    public AdUserProfile(String gbProfileName, String gbProfileDesc, int gbProfileStatus, String gbUserCreate, String gbLastUserUp, Date gbLastUpDt, Date createDt, int rowversion) {
       this.gbProfileName = gbProfileName;
       this.gbProfileDesc = gbProfileDesc;
       this.gbProfileStatus = gbProfileStatus;
       this.gbUserCreate = gbUserCreate;
       this.gbLastUserUp = gbLastUserUp;
       this.gbLastUpDt = gbLastUpDt;
       this.createDt = createDt;
       this.rowversion = rowversion;
    }
   
     @Id 

    
    @Column(name="GB_PROFILE_NAME", unique=true, nullable=false, length=100)
    public String getGbProfileName() {
        return this.gbProfileName;
    }
    
    public void setGbProfileName(String gbProfileName) {
        this.gbProfileName = gbProfileName;
    }

    
    @Column(name="GB_PROFILE_DESC", nullable=false, length=200)
    public String getGbProfileDesc() {
        return this.gbProfileDesc;
    }
    
    public void setGbProfileDesc(String gbProfileDesc) {
        this.gbProfileDesc = gbProfileDesc;
    }

    
    @Column(name="GB_PROFILE_STATUS", nullable=false, precision=22, scale=0)
    public int getGbProfileStatus() {
        return this.gbProfileStatus;
    }
    
    public void setGbProfileStatus(int gbProfileStatus) {
        this.gbProfileStatus = gbProfileStatus;
    }

    
    @Column(name="GB_USER_CREATE", nullable=false, length=20)
    public String getGbUserCreate() {
        return this.gbUserCreate;
    }
    
    public void setGbUserCreate(String gbUserCreate) {
        this.gbUserCreate = gbUserCreate;
    }

    
    @Column(name="GB_LAST_USER_UP", nullable=false, length=20)
    public String getGbLastUserUp() {
        return this.gbLastUserUp;
    }
    
    public void setGbLastUserUp(String gbLastUserUp) {
        this.gbLastUserUp = gbLastUserUp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GB_LAST_UP_DT", nullable=false)
    public Date getGbLastUpDt() {
        return this.gbLastUpDt;
    }
    
    public void setGbLastUpDt(Date gbLastUpDt) {
        this.gbLastUpDt = gbLastUpDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public int getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(int rowversion) {
        this.rowversion = rowversion;
    }
}


