package com.gabyval.persistence.user.security;
// Generated Jul 29, 2017 4:02:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdUserProfilingId generated by hbm2java
 */
@Embeddable
public class AdUserProfilingId  implements java.io.Serializable {


     private String gbProfileName;
     private String gbUsername;

    public AdUserProfilingId() {
    }

    public AdUserProfilingId(String gbProfileName, String gbUsername) {
       this.gbProfileName = gbProfileName;
       this.gbUsername = gbUsername;
    }
   


    @Column(name="GB_PROFILE_NAME", nullable=false, length=100)
    public String getGbProfileName() {
        return this.gbProfileName;
    }
    
    public void setGbProfileName(String gbProfileName) {
        this.gbProfileName = gbProfileName;
    }


    @Column(name="GB_USERNAME", nullable=false, length=20)
    public String getGbUsername() {
        return this.gbUsername;
    }
    
    public void setGbUsername(String gbUsername) {
        this.gbUsername = gbUsername;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdUserProfilingId) ) return false;
		 AdUserProfilingId castOther = ( AdUserProfilingId ) other; 
         
		 return ( (this.getGbProfileName()==castOther.getGbProfileName()) || ( this.getGbProfileName()!=null && castOther.getGbProfileName()!=null && this.getGbProfileName().equals(castOther.getGbProfileName()) ) )
 && ( (this.getGbUsername()==castOther.getGbUsername()) || ( this.getGbUsername()!=null && castOther.getGbUsername()!=null && this.getGbUsername().equals(castOther.getGbUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGbProfileName() == null ? 0 : this.getGbProfileName().hashCode() );
         result = 37 * result + ( getGbUsername() == null ? 0 : this.getGbUsername().hashCode() );
         return result;
   }   


}


