package com.gabyval.core.exception;
// Generated 4/12/2017 06:55:41 PM by Hibernate Tools 4.3.1


import com.gabyval.core.constants.GB_CommonStrConstants;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdError generated by hbm2java
 */
@Entity
@Table(name="AD_ERROR"
    ,schema="GABYVAL"
)
public class AdError  implements java.io.Serializable {


     private int gbErrorId;
     private String gbErrorDesc;
     private String gbErrorLevel;
     private Date createDt;
     private int rowversion;
     private String gbErrorTitle;
     private String gbUserCreate;
     private String gbLastUserUpd;
     private Date gbLastDtUpd;
     private int gbStatus;

    public AdError() {
    }

	
    public AdError(int gbErrorId, String gbErrorDesc, Date createDt, int rowversion) {
        this.gbErrorId = gbErrorId;
        this.gbErrorDesc = gbErrorDesc;
        this.createDt = createDt;
        this.rowversion = rowversion;
    }
    public AdError(int gbErrorId, String gbErrorDesc, String gbErrorLevel, Date createDt, int rowversion, String gbErrorTitle, String gbUserCreate, String gbLastUserUpd, Date gbLastDtUpd, int gbStatus) {
       this.gbErrorId = gbErrorId;
       this.gbErrorDesc = gbErrorDesc;
       this.gbErrorLevel = gbErrorLevel;
       this.createDt = createDt;
       this.rowversion = rowversion;
       this.gbErrorTitle = gbErrorTitle;
       this.gbUserCreate = gbUserCreate;
       this.gbLastUserUpd = gbLastUserUpd;
       this.gbLastDtUpd = gbLastDtUpd;
       this.gbStatus = gbStatus;
    }
   
     @Id 

    
    @Column(name="GB_ERROR_ID", unique=true, nullable=false, precision=22, scale=0)
    public int getGbErrorId() {
        return this.gbErrorId;
    }
    
    public void setGbErrorId(int gbErrorId) {
        this.gbErrorId = gbErrorId;
    }

    
    @Column(name="GB_ERROR_DESC", nullable=false, length=600)
    public String getGbErrorDesc() {
        return this.gbErrorDesc;
    }
    
    public void setGbErrorDesc(String gbErrorDesc) {
        this.gbErrorDesc = gbErrorDesc;
    }

    
    @Column(name="GB_ERROR_LEVEL", length=100)
    public String getGbErrorLevel() {
        return this.gbErrorLevel;
    }
    
    public void setGbErrorLevel(String gbErrorLevel) {
        this.gbErrorLevel = gbErrorLevel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public int getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(int rowversion) {
        this.rowversion = rowversion;
    }

    
    @Column(name="GB_ERROR_TITLE", length=100)
    public String getGbErrorTitle() {
        return this.gbErrorTitle;
    }
    
    public void setGbErrorTitle(String gbErrorTitle) {
        this.gbErrorTitle = gbErrorTitle;
    }

    
    @Column(name="GB_USER_CREATE", length=20)
    public String getGbUserCreate() {
        return this.gbUserCreate;
    }
    
    public void setGbUserCreate(String gbUserCreate) {
        this.gbUserCreate = gbUserCreate;
    }

    
    @Column(name="GB_LAST_USER_UPD", length=20)
    public String getGbLastUserUpd() {
        return this.gbLastUserUpd;
    }
    
    public void setGbLastUserUpd(String gbLastUserUpd) {
        this.gbLastUserUpd = gbLastUserUpd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GB_LAST_DT_UPD")
    public Date getGbLastDtUpd() {
        return this.gbLastDtUpd;
    }
    
    public void setGbLastDtUpd(Date gbLastDtUpd) {
        this.gbLastDtUpd = gbLastDtUpd;
    }

    
    @Column(name="GB_STATUS", precision=22, scale=0)
    public int getGbStatus() {
        return this.gbStatus;
    }
    
    public void setGbStatus(int gbStatus) {
        this.gbStatus = gbStatus;
    }
}


