package com.gabyval.persistence.user;
// Generated Jul 22, 2017 10:52:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdUsers generated by hbm2java
 */
@Entity
@Table(name="AD_USERS", schema="GABYVAL")
public class AdUsers  implements java.io.Serializable {
    
    private String gbUsername;
    private String gbPassword;
    private int gbLoginStatus;
    private int gbOprativeStatus;
    private Date gbLastPwdXgeDt;
    private Date gbLastLogginDt;
    private Date gbLastXgeDt;
    private String gbLastUserXge;
    private int gbUserSystem;
    private Date createDt;
    private int rowversion;
    
    public AdUsers() {
    }

    public AdUsers(String gbUsername, String gbPassword, int gbLoginStatus, int gbOprativeStatus, Date gbLastPwdXgeDt, Date gbLastLogginDt, Date gbLastXgeDt, String gbLastUserXge, int gbUserSystem, Date createDt, int rowversion) {
       this.gbUsername = gbUsername;
       this.gbPassword = gbPassword;
       this.gbLoginStatus = gbLoginStatus;
       this.gbOprativeStatus = gbOprativeStatus;
       this.gbLastPwdXgeDt = gbLastPwdXgeDt;
       this.gbLastLogginDt = gbLastLogginDt;
       this.gbLastXgeDt = gbLastXgeDt;
       this.gbLastUserXge = gbLastUserXge;
       this.gbUserSystem = gbUserSystem;
       this.createDt = createDt;
       this.rowversion = rowversion;
    }
   
    @Id
    @Column(name="GB_USERNAME", unique=true, nullable=false, length=20)
    public String getGbUsername() {
        return this.gbUsername;
    }
    
    public void setGbUsername(String gbUsername) {
        this.gbUsername = gbUsername;
    }

    
    @Column(name="GB_PASSWORD", nullable=false, length=60)
    public String getGbPassword() {
        return this.gbPassword;
    }
    
    public void setGbPassword(String gbPassword) {
        this.gbPassword = gbPassword;
    }

    
    @Column(name="GB_LOGIN_STATUS", nullable=false, precision=22, scale=0)
    public int getGbLoginStatus() {
        return this.gbLoginStatus;
    }
    
    public void setGbLoginStatus(int gbLoginStatus) {
        this.gbLoginStatus = gbLoginStatus;
    }

    
    @Column(name="GB_OPRATIVE_STATUS", nullable=false, precision=22, scale=0)
    public int getGbOprativeStatus() {
        return this.gbOprativeStatus;
    }
    
    public void setGbOprativeStatus(int gbOprativeStatus) {
        this.gbOprativeStatus = gbOprativeStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GB_LAST_PWD_XGE_DT", nullable=false, length=7)
    public Date getGbLastPwdXgeDt() {
        return this.gbLastPwdXgeDt;
    }
    
    public void setGbLastPwdXgeDt(Date gbLastPwdXgeDt) {
        this.gbLastPwdXgeDt = gbLastPwdXgeDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GB_LAST_LOGGIN_DT", nullable=false, length=7)
    public Date getGbLastLogginDt() {
        return this.gbLastLogginDt;
    }
    
    public void setGbLastLogginDt(Date gbLastLogginDt) {
        this.gbLastLogginDt = gbLastLogginDt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GB_LAST_XGE_DT", nullable=false, length=7)
    public Date getGbLastXgeDt() {
        return this.gbLastXgeDt;
    }
    
    public void setGbLastXgeDt(Date gbLastXgeDt) {
        this.gbLastXgeDt = gbLastXgeDt;
    }

    
    @Column(name="GB_LAST_USER_XGE", nullable=false, length=20)
    public String getGbLastUserXge() {
        return this.gbLastUserXge;
    }
    
    public void setGbLastUserXge(String gbLastUserXge) {
        this.gbLastUserXge = gbLastUserXge;
    }

    
    @Column(name="GB_USER_SYSTEM", nullable=false, precision=22, scale=0)
    public int getGbUserSystem() {
        return this.gbUserSystem;
    }
    
    public void setGbUserSystem(int gbUserSystem) {
        this.gbUserSystem = gbUserSystem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public int getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(int rowversion) {
        this.rowversion = rowversion;
    }
}


