package com.gabyval.persistence.user;
// Generated Sep 7, 2017 4:19:29 PM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdUserPersonalData generated by hbm2java
 */
@Entity
@Table(name="AD_USER_PERSONAL_DATA"
    ,schema="GABYVAL"
)
public class AdUserPersonalData  implements java.io.Serializable {


     private String gbUsername;
     private String gbStaffName;
     private String gbStaffSurname;
     private int gbIdType;
     private String gbIdNumber;
     private Blob gbPhoto;
     private String gbPhoneNumber;
     private String gbMobileNumber;
     private String gbEmail;
     private Date gbBirthdate;
     private int gbGender;
     private Date createDt;
     private int rowversion;

    public AdUserPersonalData() {
    }

	
    public AdUserPersonalData(String gbUsername, String gbStaffName, String gbStaffSurname, int gbIdType, String gbIdNumber, Date createDt, int rowversion) {
        this.gbUsername = gbUsername;
        this.gbStaffName = gbStaffName;
        this.gbStaffSurname = gbStaffSurname;
        this.gbIdType = gbIdType;
        this.gbIdNumber = gbIdNumber;
        this.createDt = createDt;
        this.rowversion = rowversion;
    }
    public AdUserPersonalData(String gbUsername, String gbStaffName, String gbStaffSurname, int gbIdType, String gbIdNumber, Blob gbPhoto, String gbPhoneNumber, String gbMobileNumber, String gbEmail, Date gbBirthdate, int gbGender, Date createDt, int rowversion) {
       this.gbUsername = gbUsername;
       this.gbStaffName = gbStaffName;
       this.gbStaffSurname = gbStaffSurname;
       this.gbIdType = gbIdType;
       this.gbIdNumber = gbIdNumber;
       this.gbPhoto = gbPhoto;
       this.gbPhoneNumber = gbPhoneNumber;
       this.gbMobileNumber = gbMobileNumber;
       this.gbEmail = gbEmail;
       this.gbBirthdate = gbBirthdate;
       this.gbGender = gbGender;
       this.createDt = createDt;
       this.rowversion = rowversion;
    }
   
     @Id 

    
    @Column(name="GB_USERNAME", unique=true, nullable=false, length=20)
    public String getGbUsername() {
        return this.gbUsername;
    }
    
    public void setGbUsername(String gbUsername) {
        this.gbUsername = gbUsername;
    }

    
    @Column(name="GB_STAFF_NAME", nullable=false, length=200)
    public String getGbStaffName() {
        return this.gbStaffName;
    }
    
    public void setGbStaffName(String gbStaffName) {
        this.gbStaffName = gbStaffName;
    }

    
    @Column(name="GB_STAFF_SURNAME", nullable=false, length=200)
    public String getGbStaffSurname() {
        return this.gbStaffSurname;
    }
    
    public void setGbStaffSurname(String gbStaffSurname) {
        this.gbStaffSurname = gbStaffSurname;
    }

    
    @Column(name="GB_ID_TYPE", nullable=false, precision=22, scale=0)
    public int getGbIdType() {
        return this.gbIdType;
    }
    
    public void setGbIdType(int gbIdType) {
        this.gbIdType = gbIdType;
    }

    
    @Column(name="GB_ID_NUMBER", nullable=false, length=20)
    public String getGbIdNumber() {
        return this.gbIdNumber;
    }
    
    public void setGbIdNumber(String gbIdNumber) {
        this.gbIdNumber = gbIdNumber;
    }

    
    @Column(name="GB_PHOTO")
    public Blob getGbPhoto() {
        return this.gbPhoto;
    }
    
    public void setGbPhoto(Blob gbPhoto) {
        this.gbPhoto = gbPhoto;
    }

    
    @Column(name="GB_PHONE_NUMBER", length=20)
    public String getGbPhoneNumber() {
        return this.gbPhoneNumber;
    }
    
    public void setGbPhoneNumber(String gbPhoneNumber) {
        this.gbPhoneNumber = gbPhoneNumber;
    }

    
    @Column(name="GB_MOBILE_NUMBER", length=20)
    public String getGbMobileNumber() {
        return this.gbMobileNumber;
    }
    
    public void setGbMobileNumber(String gbMobileNumber) {
        this.gbMobileNumber = gbMobileNumber;
    }

    
    @Column(name="GB_EMAIL", length=200)
    public String getGbEmail() {
        return this.gbEmail;
    }
    
    public void setGbEmail(String gbEmail) {
        this.gbEmail = gbEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="GB_BIRTHDATE", length=7)
    public Date getGbBirthdate() {
        return this.gbBirthdate;
    }
    
    public void setGbBirthdate(Date gbBirthdate) {
        this.gbBirthdate = gbBirthdate;
    }

    
    @Column(name="GB_GENDER", precision=22, scale=0)
    public int getGbGender() {
        return this.gbGender;
    }
    
    public void setGbGender(int gbGender) {
        this.gbGender = gbGender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DT", nullable=false, length=7)
    public Date getCreateDt() {
        return this.createDt;
    }
    
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    
    @Column(name="ROWVERSION", nullable=false, precision=22, scale=0)
    public int getRowversion() {
        return this.rowversion;
    }
    
    public void setRowversion(int rowversion) {
        this.rowversion = rowversion;
    }




}


