/* ***************************************************************************************************************************************************
 * ***************************************************************************************************************************************************
 * ***************************************************************************************************************************************************
 * *******************************                                                                              **************************************
 * *******************************	********** ********** ******    **      ** **      ** ********** **         **************************************
 * *******************************	********** **********  ******   **      ** **      ** ********** **         **************************************
 * *******************************	**         **      **  **  **   **      ** **      ** **      ** **         **************************************
 * *******************************	**         **      **  **  **   **      ** **      ** **      ** **         **************************************
 * *******************************  **         **      **  ******    **    **  **      ** **      ** **         **************************************
 * *******************************  **    **** **********  *******    **  **   **      ** ********** **         **************************************
 * *******************************  **    **** **********  ********    ****    **      ** ********** **         **************************************
 * *******************************  **      ** **      **  **    **     **     **      ** **      ** **         **************************************
 * *******************************  **      ** **      **  **    **     **      **    **  **      ** **         **************************************
 * *******************************  **      ** **      **  **   **      **       **  **   **      ** **         **************************************
 * *******************************  ********** **      **  **  **       **        ****    **      ** ********** **************************************
 * *******************************  ********** **      ** ******        **         **     **      ** ********** **************************************
 * ***************************************************************************************************************************************************
 * ***************************************************************************************************************************************************
 * ***************************************************************************************************************************************************
 *_____Nombre del Archivo___________|_____VERSION_______|_________________AUTOR_________________|___________echa de creacion/modificacion____________|
 *	    ins_db_app_user		     	|		1.0			|    GUSTAVO ADOLFO OVALLE QUINTERO		|			   		26/03/2017      			     |
 *****************************************************************************************************************************************************/
 
/* *****************************************************************************
 * Creacion del perfil de usuario
 * ****************************************************************************/
CREATE PROFILE "GABYVALPRO" LIMIT CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME DEFAULT
SESSIONS_PER_USER UNLIMITED
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME DEFAULT
PASSWORD_GRACE_TIME DEFAULT
PASSWORD_REUSE_MAX DEFAULT
PASSWORD_REUSE_TIME DEFAULT
PASSWORD_LOCK_TIME DEFAULT
FAILED_LOGIN_ATTEMPTS DEFAULT
PASSWORD_VERIFY_FUNCTION DEFAULT;

/* *****************************************************************************
 * Creacion de los TABLESPACE CAMBIAR LUGAR DE CREACION DEL DATAFILE...
 * ****************************************************************************/
CREATE BIGFILE TABLESPACE "TEGABIVAL" DATAFILE 'C:\app\GABYVAL\TEGABYVAL' SIZE 50M REUSE AUTOEXTEND ON NEXT 50M MAXSIZE 
	   UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
	   
/* *****************************************************************************
 * Creacion del usuario de aplicacion.
 * ****************************************************************************/
CREATE USER "GABYVAL" IDENTIFIED BY "GabybalTata1027" DEFAULT TABLESPACE "TEGABIVAL" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
ALTER USER "GABYVAL" PROFILE "GABYVALPRO";
GRANT ADMINISTER ANY SQL TUNING SET TO "GABYVAL";
GRANT ADMINISTER DATABASE TRIGGER TO "GABYVAL"; 
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "GABYVAL";
GRANT ADMINISTER SQL TUNING SET TO "GABYVAL";
GRANT ADVISOR TO "GABYVAL";
GRANT ALTER ANY ASSEMBLY TO "GABYVAL";
GRANT ALTER ANY CLUSTER TO "GABYVAL";
GRANT ALTER ANY CUBE TO "GABYVAL";
GRANT ALTER ANY CUBE DIMENSION TO "GABYVAL";
GRANT ALTER ANY DIMENSION TO "GABYVAL";
GRANT ALTER ANY EDITION TO "GABYVAL";
GRANT ALTER ANY EVALUATION CONTEXT TO "GABYVAL";
GRANT ALTER ANY INDEX TO "GABYVAL";
GRANT ALTER ANY INDEXTYPE TO "GABYVAL";
GRANT ALTER ANY LIBRARY TO "GABYVAL";
GRANT ALTER ANY MATERIALIZED VIEW TO "GABYVAL";
GRANT ALTER ANY MINING MODEL TO "GABYVAL";
GRANT ALTER ANY OPERATOR TO "GABYVAL";
GRANT ALTER ANY OUTLINE TO "GABYVAL";
GRANT ALTER ANY PROCEDURE TO "GABYVAL";
GRANT ALTER ANY ROLE TO "GABYVAL";
GRANT ALTER ANY RULE TO "GABYVAL";
GRANT ALTER ANY RULE SET TO "GABYVAL";
GRANT ALTER ANY SEQUENCE TO "GABYVAL";
GRANT ALTER ANY SQL PROFILE TO "GABYVAL";
GRANT ALTER ANY TABLE TO "GABYVAL";
GRANT ALTER ANY TRIGGER TO "GABYVAL";
GRANT ALTER ANY TYPE TO "GABYVAL";
GRANT ALTER DATABASE TO "GABYVAL";
GRANT ALTER PROFILE TO "GABYVAL";
GRANT ALTER RESOURCE COST TO "GABYVAL";
GRANT ALTER ROLLBACK SEGMENT TO "GABYVAL";
GRANT ALTER SESSION TO "GABYVAL";
GRANT ALTER SYSTEM TO "GABYVAL";
GRANT ALTER TABLESPACE TO "GABYVAL";
GRANT ALTER USER TO "GABYVAL";
GRANT ANALYZE ANY TO "GABYVAL";
GRANT ANALYZE ANY DICTIONARY TO "GABYVAL";
GRANT AUDIT ANY TO "GABYVAL";
GRANT AUDIT SYSTEM TO "GABYVAL";
GRANT BACKUP ANY TABLE TO "GABYVAL";
GRANT BECOME USER TO "GABYVAL";
GRANT CHANGE NOTIFICATION TO "GABYVAL";
GRANT COMMENT ANY MINING MODEL TO "GABYVAL";
GRANT COMMENT ANY TABLE TO "GABYVAL";
GRANT CREATE ANY ASSEMBLY TO "GABYVAL";
GRANT CREATE ANY CLUSTER TO "GABYVAL";
GRANT CREATE ANY CONTEXT TO "GABYVAL";
GRANT CREATE ANY CUBE TO "GABYVAL";
GRANT CREATE ANY CUBE BUILD PROCESS TO "GABYVAL";
GRANT CREATE ANY CUBE DIMENSION TO "GABYVAL";
GRANT CREATE ANY DIMENSION TO "GABYVAL";
GRANT CREATE ANY DIRECTORY TO "GABYVAL";
GRANT CREATE ANY EDITION TO "GABYVAL";
GRANT CREATE ANY EVALUATION CONTEXT TO "GABYVAL";
GRANT CREATE ANY INDEX TO "GABYVAL";
GRANT CREATE ANY INDEXTYPE TO "GABYVAL";
GRANT CREATE ANY JOB TO "GABYVAL";
GRANT CREATE ANY LIBRARY TO "GABYVAL";
GRANT CREATE ANY MATERIALIZED VIEW TO "GABYVAL";
GRANT CREATE ANY MEASURE FOLDER TO "GABYVAL";
GRANT CREATE ANY MINING MODEL TO "GABYVAL";
GRANT CREATE ANY OPERATOR TO "GABYVAL";
GRANT CREATE ANY OUTLINE TO "GABYVAL";
GRANT CREATE ANY PROCEDURE TO "GABYVAL";
GRANT CREATE ANY RULE TO "GABYVAL";
GRANT CREATE ANY RULE SET TO "GABYVAL";
GRANT CREATE ANY SEQUENCE TO "GABYVAL";
GRANT CREATE ANY SQL PROFILE TO "GABYVAL";
GRANT CREATE ANY SYNONYM TO "GABYVAL";
GRANT CREATE ANY TABLE TO "GABYVAL";
GRANT CREATE ANY TRIGGER TO "GABYVAL";
GRANT CREATE ANY TYPE TO "GABYVAL";
GRANT CREATE ANY VIEW TO "GABYVAL";
GRANT CREATE ASSEMBLY TO "GABYVAL";
GRANT CREATE CLUSTER TO "GABYVAL";
GRANT CREATE CUBE TO "GABYVAL";
GRANT CREATE CUBE BUILD PROCESS TO "GABYVAL";
GRANT CREATE CUBE DIMENSION TO "GABYVAL";
GRANT CREATE DATABASE LINK TO "GABYVAL";
GRANT CREATE DIMENSION TO "GABYVAL";
GRANT CREATE EVALUATION CONTEXT TO "GABYVAL";
GRANT CREATE EXTERNAL JOB TO "GABYVAL";
GRANT CREATE INDEXTYPE TO "GABYVAL";
GRANT CREATE JOB TO "GABYVAL";
GRANT CREATE LIBRARY TO "GABYVAL";
GRANT CREATE MATERIALIZED VIEW TO "GABYVAL";
GRANT CREATE MEASURE FOLDER TO "GABYVAL";
GRANT CREATE MINING MODEL TO "GABYVAL";
GRANT CREATE OPERATOR TO "GABYVAL";
GRANT CREATE PROCEDURE TO "GABYVAL";
GRANT CREATE PROFILE TO "GABYVAL";
GRANT CREATE PUBLIC DATABASE LINK TO "GABYVAL";
GRANT CREATE PUBLIC SYNONYM TO "GABYVAL";
GRANT CREATE ROLE TO "GABYVAL";
GRANT CREATE ROLLBACK SEGMENT TO "GABYVAL";
GRANT CREATE RULE TO "GABYVAL";
GRANT CREATE RULE SET TO "GABYVAL";
GRANT CREATE SEQUENCE TO "GABYVAL";
GRANT CREATE SESSION TO "GABYVAL";
GRANT CREATE SYNONYM TO "GABYVAL";
GRANT CREATE TABLE TO "GABYVAL";
GRANT CREATE TABLESPACE TO "GABYVAL";
GRANT CREATE TRIGGER TO "GABYVAL";
GRANT CREATE TYPE TO "GABYVAL";
GRANT CREATE USER TO "GABYVAL";
GRANT CREATE VIEW TO "GABYVAL"; 
GRANT DEBUG ANY PROCEDURE TO "GABYVAL";
GRANT DEBUG CONNECT SESSION TO "GABYVAL";
GRANT DELETE ANY CUBE DIMENSION TO "GABYVAL";
GRANT DELETE ANY MEASURE FOLDER TO "GABYVAL";
GRANT DELETE ANY TABLE TO "GABYVAL"; 
GRANT DROP ANY ASSEMBLY TO "GABYVAL";
GRANT DROP ANY CLUSTER TO "GABYVAL";
GRANT DROP ANY CONTEXT TO "GABYVAL";
GRANT DROP ANY CUBE TO "GABYVAL";
GRANT DROP ANY CUBE BUILD PROCESS TO "GABYVAL";
GRANT DROP ANY CUBE DIMENSION TO "GABYVAL";
GRANT DROP ANY DIMENSION TO "GABYVAL";
GRANT DROP ANY DIRECTORY TO "GABYVAL";
GRANT DROP ANY EDITION TO "GABYVAL";
GRANT DROP ANY EVALUATION CONTEXT TO "GABYVAL";
GRANT DROP ANY INDEX TO "GABYVAL";
GRANT DROP ANY INDEXTYPE TO "GABYVAL";
GRANT DROP ANY LIBRARY TO "GABYVAL";
GRANT DROP ANY MATERIALIZED VIEW TO "GABYVAL";
GRANT DROP ANY MEASURE FOLDER TO "GABYVAL";
GRANT DROP ANY MINING MODEL TO "GABYVAL";
GRANT DROP ANY OPERATOR TO "GABYVAL";
GRANT DROP ANY OUTLINE TO "GABYVAL";
GRANT DROP ANY PROCEDURE TO "GABYVAL";
GRANT DROP ANY ROLE TO "GABYVAL";
GRANT DROP ANY RULE TO "GABYVAL";
GRANT DROP ANY RULE SET TO "GABYVAL";
GRANT DROP ANY SEQUENCE TO "GABYVAL";
GRANT DROP ANY SQL PROFILE TO "GABYVAL";
GRANT DROP ANY SYNONYM TO "GABYVAL";
GRANT DROP ANY TABLE TO "GABYVAL";
GRANT DROP ANY TRIGGER TO "GABYVAL";
GRANT DROP ANY TYPE TO "GABYVAL";
GRANT DROP ANY VIEW TO "GABYVAL";
GRANT DROP PROFILE TO "GABYVAL";
GRANT DROP PUBLIC DATABASE LINK TO "GABYVAL";
GRANT DROP PUBLIC SYNONYM TO "GABYVAL";
GRANT DROP ROLLBACK SEGMENT TO "GABYVAL";
GRANT DROP TABLESPACE TO "GABYVAL";
GRANT DROP USER TO "GABYVAL";
GRANT EXECUTE ANY ASSEMBLY TO "GABYVAL";
GRANT EXECUTE ANY CLASS TO "GABYVAL";
GRANT EXECUTE ANY EVALUATION CONTEXT TO "GABYVAL";
GRANT EXECUTE ANY INDEXTYPE TO "GABYVAL";
GRANT EXECUTE ANY LIBRARY TO "GABYVAL";
GRANT EXECUTE ANY OPERATOR TO "GABYVAL";
GRANT EXECUTE ANY PROCEDURE TO "GABYVAL";
GRANT EXECUTE ANY PROGRAM TO "GABYVAL";
GRANT EXECUTE ANY RULE TO "GABYVAL";
GRANT EXECUTE ANY RULE SET TO "GABYVAL";
GRANT EXECUTE ANY TYPE TO "GABYVAL";
GRANT EXECUTE ASSEMBLY TO "GABYVAL";
GRANT EXPORT FULL DATABASE TO "GABYVAL";
GRANT FLASHBACK ANY TABLE TO "GABYVAL";
GRANT FLASHBACK ARCHIVE ADMINISTER TO "GABYVAL";
GRANT FORCE ANY TRANSACTION TO "GABYVAL";
GRANT FORCE TRANSACTION TO "GABYVAL"; 

GRANT GLOBAL QUERY REWRITE TO "GABYVAL";
GRANT GRANT ANY OBJECT PRIVILEGE TO "GABYVAL";
GRANT GRANT ANY PRIVILEGE TO "GABYVAL";
GRANT GRANT ANY ROLE TO "GABYVAL";
GRANT IMPORT FULL DATABASE TO "GABYVAL";
GRANT INSERT ANY CUBE DIMENSION TO "GABYVAL";
GRANT INSERT ANY MEASURE FOLDER TO "GABYVAL";
GRANT INSERT ANY TABLE TO "GABYVAL";
GRANT LOCK ANY TABLE TO "GABYVAL";
GRANT MANAGE ANY FILE GROUP TO "GABYVAL";
GRANT MANAGE FILE GROUP TO "GABYVAL";
GRANT MANAGE SCHEDULER TO "GABYVAL";
GRANT MANAGE TABLESPACE TO "GABYVAL";
GRANT MERGE ANY VIEW TO "GABYVAL";
GRANT ON COMMIT REFRESH TO "GABYVAL";
GRANT QUERY REWRITE TO "GABYVAL";
GRANT READ ANY FILE GROUP TO "GABYVAL";
GRANT RESTRICTED SESSION TO "GABYVAL";
GRANT RESUMABLE TO "GABYVAL";
GRANT SELECT ANY CUBE TO "GABYVAL";
GRANT SELECT ANY CUBE DIMENSION TO "GABYVAL";
GRANT SELECT ANY DICTIONARY TO "GABYVAL";
GRANT SELECT ANY MINING MODEL TO "GABYVAL";
GRANT SELECT ANY SEQUENCE TO "GABYVAL";
GRANT SELECT ANY TABLE TO "GABYVAL";
GRANT SELECT ANY TRANSACTION TO "GABYVAL";
GRANT SYSDBA TO "GABYVAL" WITH ADMIN OPTION;
GRANT SYSOPER TO "GABYVAL" WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO "GABYVAL";
GRANT UNDER ANY TYPE TO "GABYVAL";
GRANT UNDER ANY VIEW TO "GABYVAL";
GRANT UNLIMITED TABLESPACE TO "GABYVAL";
GRANT UPDATE ANY CUBE TO "GABYVAL";
GRANT UPDATE ANY CUBE BUILD PROCESS TO "GABYVAL";
GRANT UPDATE ANY CUBE DIMENSION TO "GABYVAL";
GRANT UPDATE ANY TABLE TO "GABYVAL";
GRANT "CONNECT" TO "GABYVAL" WITH ADMIN OPTION;
COMMIT;